package lab.aikibo.uji.kendaraan.app.ui;

import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import lab.aikibo.uji.kendaraan.app.MainApp;
import lab.aikibo.uji.kendaraan.app.entity.AdmKendaraan;
import lab.aikibo.uji.kendaraan.app.entity.RefBahanBakar;
import lab.aikibo.uji.kendaraan.app.entity.RefBahanKaroseri;
import lab.aikibo.uji.kendaraan.app.entity.RefJnsKendaraan;
import lab.aikibo.uji.kendaraan.app.entity.RefJnsRumah;

public class AdmKendaraanUI extends javax.swing.JFrame {
    
    MainApp mainApp;
    AdmKendaraan dataKendaraan;

    /**
     * Creates new form AdmKendaraanUI
     */
    public AdmKendaraanUI() {
        initComponents();
        initData();
    }
    
    public AdmKendaraanUI(MainApp mainApp) {
        this.mainApp = mainApp;
        initComponents();
        initData();
    }
    
    private void initData() {
        Iterator<RefJnsKendaraan> dataKendaraan = mainApp.getRefJnsKendaraanRepo().findAllByOrderByIdAsc().iterator();
        DefaultComboBoxModel jnsKendaraanModel = new DefaultComboBoxModel();
        while(dataKendaraan.hasNext()) {
            RefJnsKendaraan data = dataKendaraan.next();
            jnsKendaraanModel.addElement(data.getJnsKendaraan());
        }
        cbJenisKendaraan.setModel(jnsKendaraanModel);
        
        Iterator<RefBahanBakar> dataBahanBakar = mainApp.getBahanBakarRepo().findAllByOrderById().iterator();
        DefaultComboBoxModel bahanBakarModel = new DefaultComboBoxModel();
        while(dataBahanBakar.hasNext()) {
            RefBahanBakar data = dataBahanBakar.next();
            bahanBakarModel.addElement(data.getBahanBakar());
        }
        cbBahanBakar.setModel(bahanBakarModel);
        
        Iterator<RefJnsRumah> dataRumah = mainApp.getRefJnsRumahRepo().findAllByOrderById().iterator();
        DefaultComboBoxModel rumahModel = new DefaultComboBoxModel();
        while(dataRumah.hasNext()) {
            RefJnsRumah data = dataRumah.next();
            rumahModel.addElement(data.getJnsRumah());
        }
        cbJnsRumah.setModel(rumahModel);
        
        Iterator<RefBahanKaroseri> dataBahanKaroseri = mainApp.getBahanKaroseriRepo().findAllByOrderById().iterator();
        DefaultComboBoxModel bahanKaroseriModel = new DefaultComboBoxModel();
        while(dataBahanKaroseri.hasNext()) {
            RefBahanKaroseri data = dataBahanKaroseri.next();
            bahanKaroseriModel.addElement(data.getBahan());
        }
        cbBahanKaroseri.setModel(bahanKaroseriModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNoken = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfPemilik = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfAlamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfMerk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfTipe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfTahunPembuatan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbJenisKendaraan = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbBahanBakar = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbJnsRumah = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        tfNomorUji = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfNomorRangka = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfNomorMesin = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbBahanKaroseri = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setTitle("Data Administrasi Kendaraan");
        setAlwaysOnTop(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Nomor Kendaraan");

        tfNoken.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNokenFocusGained(evt);
            }
        });

        jLabel2.setText("Nama Pemilik");

        jLabel3.setText("Alamat");

        jLabel4.setText("Merk");

        jLabel5.setText("Tipe");

        jLabel6.setText("Tahun");

        jLabel7.setText("Jenis Kendaraan");

        cbJenisKendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbJenisKendaraan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbJenisKendaraanItemStateChanged(evt);
            }
        });

        jLabel8.setText("Bahan Bakar");

        cbBahanBakar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Jenis Rumah-Rumah");

        cbJnsRumah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Nomor Uji");

        jLabel11.setText("Nomor Rangka");

        jLabel12.setText("Nomor Mesin");

        jLabel13.setText("Bahan Karoseri");

        cbBahanKaroseri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBatal)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal)
                    .addComponent(btnSimpan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfMerk, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTahunPembuatan, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNoken, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPemilik, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbJenisKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbBahanBakar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbJnsRumah, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNomorUji)
                                    .addComponent(tfNomorMesin)
                                    .addComponent(cbBahanKaroseri, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNomorRangka)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNoken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfPemilik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfTahunPembuatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbJenisKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbBahanBakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbJnsRumah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfNomorUji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tfNomorRangka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfNomorMesin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbBahanKaroseri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        setVisible(false);
        mainApp.fEntrySkrd.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        setVisible(false);
        mainApp.fEntrySkrd.setEnabled(true);
    }//GEN-LAST:event_formComponentHidden

    private void tfNokenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNokenFocusGained
        if(tfNoken.getText().trim().equals("")) return;
        List<AdmKendaraan> data = mainApp.getAdmKendaraanRepo().findByNomorKendaraan(tfNoken.getText());
        dataKendaraan = data.get(0);
        tfPemilik.setText(dataKendaraan.getNamaPemilik());
        tfAlamat.setText(dataKendaraan.getAlamat());
        tfMerk.setText(dataKendaraan.getMerk());
        tfTipe.setText(dataKendaraan.getTipe());
        tfTahunPembuatan.setText(dataKendaraan.getThnPembuatan());
        cbJenisKendaraan.setSelectedIndex(dataKendaraan.getIdJnsKendaraan()-1);
        cbBahanBakar.setSelectedIndex(dataKendaraan.getIdJnsBahanBakar()-1);
        System.out.println("Jenis Rumah: " + dataKendaraan.getIdJnsRumah());
        cbJnsRumah.setSelectedIndex(dataKendaraan.getIdJnsRumah()-1);
        tfNomorUji.setText(dataKendaraan.getNoUji());
        tfNomorRangka.setText(dataKendaraan.getNoRangka());
        tfNomorMesin.setText(dataKendaraan.getNoMesin());
        cbBahanKaroseri.setSelectedIndex(dataKendaraan.getIdBahanKeroseri()-1);
    }//GEN-LAST:event_tfNokenFocusGained

    private void cbJenisKendaraanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbJenisKendaraanItemStateChanged
        Iterator<RefJnsRumah> dataRumah = mainApp.getRefJnsRumahRepo().findByIdJnsKendaraanOrderById(cbJenisKendaraan.getSelectedIndex()+1).iterator();
        DefaultComboBoxModel rumahModel = new DefaultComboBoxModel();
        while(dataRumah.hasNext()) {
            RefJnsRumah data = dataRumah.next();
            rumahModel.addElement(data.getJnsRumah());
        }
        cbJnsRumah.setModel(rumahModel);
    }//GEN-LAST:event_cbJenisKendaraanItemStateChanged

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        mainApp.fEntrySkrd.setEnabled(true);
        setVisible(false);
        clearForm();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if(tfNoken.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Data tidak lengkap");
            return;
        }
        
        dataKendaraan.setNomorKendaraan(tfNoken.getText());
        dataKendaraan.setNamaPemilik(tfPemilik.getText());
        dataKendaraan.setAlamat(tfAlamat.getText());
        dataKendaraan.setMerk(tfMerk.getText());
        dataKendaraan.setTipe(tfTipe.getText());
        dataKendaraan.setThnPembuatan(tfTahunPembuatan.getText());
        dataKendaraan.setIdJnsKendaraan(cbJenisKendaraan.getSelectedIndex()+1);
        dataKendaraan.setIdJnsBahanBakar(cbBahanBakar.getSelectedIndex()+1);
        dataKendaraan.setIdJnsRumah(cbJnsRumah.getSelectedIndex()+1);
        dataKendaraan.setNoUji(tfNomorUji.getText());
        dataKendaraan.setNoRangka(tfNomorRangka.getText());
        dataKendaraan.setNoMesin(tfNomorMesin.getText());
        dataKendaraan.setIdBahanKeroseri(cbBahanKaroseri.getSelectedIndex()+1);
        
        mainApp.getAdmKendaraanRepo().save(dataKendaraan);
        JOptionPane.showMessageDialog(this, "Data Kendaraan Sudah Tersimpan");
        
        mainApp.fEntrySkrd.setEnabled(true);
        setVisible(false);
        clearForm();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void clearForm() {
        tfNoken.setText("");
        tfPemilik.setText("");
        tfAlamat.setText("");
        tfMerk.setText("");
        tfTipe.setText("");
        tfTahunPembuatan.setText("");
        cbJenisKendaraan.setSelectedIndex(0);
        cbBahanBakar.setSelectedIndex(0);
        cbJnsRumah.setSelectedIndex(0);
        tfNomorUji.setText("");
        tfNomorRangka.setText("");
        tfNomorMesin.setText("");
        cbBahanKaroseri.setSelectedIndex(0);
        
        dataKendaraan = new AdmKendaraan();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmKendaraanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmKendaraanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmKendaraanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmKendaraanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmKendaraanUI().setVisible(true);
            }
        });
    }
    
    public JTextField getTfNoken() {
        return tfNoken;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbBahanBakar;
    private javax.swing.JComboBox<String> cbBahanKaroseri;
    private javax.swing.JComboBox<String> cbJenisKendaraan;
    private javax.swing.JComboBox<String> cbJnsRumah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfMerk;
    private javax.swing.JTextField tfNoken;
    private javax.swing.JTextField tfNomorMesin;
    private javax.swing.JTextField tfNomorRangka;
    private javax.swing.JTextField tfNomorUji;
    private javax.swing.JTextField tfPemilik;
    private javax.swing.JTextField tfTahunPembuatan;
    private javax.swing.JTextField tfTipe;
    // End of variables declaration//GEN-END:variables
}
