/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lab.aikibo.uji.kendaraan.app.ui;

import java.math.BigDecimal;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import javax.swing.text.NumberFormatter;
import lab.aikibo.uji.kendaraan.app.MainApp;
import lab.aikibo.uji.kendaraan.app.entity.AdmKendaraan;
import lab.aikibo.uji.kendaraan.app.entity.RefBiayaBukuUji;
import lab.aikibo.uji.kendaraan.app.entity.RefJnsKendaraan;
import lab.aikibo.uji.kendaraan.app.entity.RefJnsRumah;
import lab.aikibo.uji.kendaraan.app.entity.RefPejabat;
import lab.aikibo.uji.kendaraan.app.entity.Skrd;
import lab.aikibo.uji.kendaraan.app.repo.AdmKendaraanRepo;
import org.joda.time.LocalDate;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author tamami <tamami.oka@gmail.com>
 */
public class EntrySkrdUI extends javax.swing.JFrame {
    
    MainApp mainApp;
    NumberFormat indoFormat;
    Locale idLocale;
    LocalDate tglHabisUji;
    DefaultComboBoxModel<String> daftarPejabat = new DefaultComboBoxModel<String>();
    Skrd skrd;
    
    /** Creates new form EntrySkrdUI */
    public EntrySkrdUI() {
        initComponents();
        initData();
    }
    
    private void initData() {
        dpTglDaftar.setDate(new Date());
        tglHabisUji = LocalDate.now().plusMonths(6);
        
        cbJenisKendaraan.removeAllItems();
        Iterator<RefJnsKendaraan> dataJnsKendaraan = mainApp.getRefJnsKendaraanRepo().findAll().iterator();
        while(dataJnsKendaraan.hasNext()) {
            cbJenisKendaraan.addItem(dataJnsKendaraan.next().getJnsKendaraan());
        }
        
        try {
            tfTahunPembuatan.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("####")));
        } catch (ParseException ex) {
            System.out.println("Error saat pembuatan format tahun pembuatan kendaraan");
        }
        
        idLocale = Locale.forLanguageTag("in_ID");
        
        indoFormat = NumberFormat.getNumberInstance(Locale.forLanguageTag("in_ID"));
        tfBiayaBukuUji.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(indoFormat)));
        tfBiayaPemeriksaan.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(indoFormat)));
        tfBiayaAdm.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(indoFormat)));
        tfBiayaTandaUji.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(indoFormat)));
        tfPokokRetribusi.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(indoFormat)));
        tfDenda.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(indoFormat)));
        dpTglHabisUji.setDate(tglHabisUji.toDate());
        
        cbNamaPejabat.removeAllItems();
        cbNamaPejabat.setModel(daftarPejabat);
        Iterator<RefPejabat> dataPejabat = mainApp.getRefPejabatRepo().findAll().iterator();
        while(dataPejabat.hasNext()) {
            cbNamaPejabat.addItem(dataPejabat.next().getNama());
        }
        
        updateJabatan();
    }
    
    private void updateJabatan() {
        if(cbNamaPejabat.getSelectedItem() != null) {
            List<RefPejabat> listDataPejabat = mainApp.getRefPejabatRepo().findByNama((String) cbNamaPejabat.getSelectedItem());
            tfJabatan.setText(listDataPejabat.get(0).getJabatan());
        }
    }
    
    public EntrySkrdUI(MainApp mainApp) {
        this.mainApp = mainApp;
        initComponents();
        initData();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpGantiBuku = new javax.swing.ButtonGroup();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        dpTglDaftar = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        tfNoUji = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnCetakSkrd = new javax.swing.JButton();
        btnCetakFormPendaftaran = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnDataBaru = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfNoken = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfPemilik = new javax.swing.JTextField();
        tfAlamat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbJenisKendaraan = new javax.swing.JComboBox<>();
        cbJnsRumah = new javax.swing.JComboBox<>();
        tfTahunPembuatan = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        tfJnsPengujian = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rbYa = new javax.swing.JRadioButton();
        rbTidak = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfBiayaBukuUji = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        tfBiayaPemeriksaan = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        tfBiayaTandaSamping = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        tfBiayaAdm = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        tfBiayaTandaUji = new javax.swing.JFormattedTextField();
        tfPokokRetribusi = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        dpTglHabisUji = new org.jdesktop.swingx.JXDatePicker();
        jLabel17 = new javax.swing.JLabel();
        dpTglHabisUjiLalu = new org.jdesktop.swingx.JXDatePicker();
        jLabel18 = new javax.swing.JLabel();
        tfDenda = new javax.swing.JFormattedTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        tfBiaya = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        cbNamaPejabat = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        tfJabatan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PENDAFTARAN PENGUJIAN");

        jLabel1.setText("Tgl Pendaftaran");

        jLabel2.setText("No Uji");

        tfNoUji.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNoUjiFocusLost(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnCetakSkrd.setText("SKRD");
        btnCetakSkrd.setEnabled(false);

        btnCetakFormPendaftaran.setText("Formulir Pendaftaran");
        btnCetakFormPendaftaran.setEnabled(false);

        btnSimpan.setMnemonic('S');
        btnSimpan.setText("Simpan");
        btnSimpan.setToolTipText("");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnDataBaru.setMnemonic('D');
        btnDataBaru.setText("Data Baru");
        btnDataBaru.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDataBaru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCetakFormPendaftaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCetakSkrd)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCetakSkrd)
                    .addComponent(btnCetakFormPendaftaran)
                    .addComponent(btnSimpan)
                    .addComponent(btnDataBaru))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Nomor Kendaraan");

        jLabel4.setText("Pemilik");

        jLabel5.setText("Alamat");

        tfPemilik.setEditable(false);

        tfAlamat.setEditable(false);

        jLabel6.setText("Jenis Kendaraan");

        cbJenisKendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbJenisKendaraan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbJenisKendaraanItemStateChanged(evt);
            }
        });

        cbJnsRumah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Jenis Pengujian");

        tfJnsPengujian.setEditable(false);
        tfJnsPengujian.setText("BERKALA");

        jLabel8.setText("Ganti Buku");

        btnGrpGantiBuku.add(rbYa);
        rbYa.setText("Ya");
        rbYa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbYaItemStateChanged(evt);
            }
        });

        btnGrpGantiBuku.add(rbTidak);
        rbTidak.setText("Tidak");
        rbTidak.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbTidakItemStateChanged(evt);
            }
        });

        jLabel9.setText("Retribusi");

        jLabel10.setText("Buku Uji");

        tfBiayaBukuUji.setEditable(false);
        tfBiayaBukuUji.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel11.setText("Pemeriksaan");

        tfBiayaPemeriksaan.setEditable(false);
        tfBiayaPemeriksaan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel12.setText("Tanda Samping");

        tfBiayaTandaSamping.setEditable(false);
        tfBiayaTandaSamping.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel13.setText("Biaya Administrasi");

        tfBiayaAdm.setEditable(false);
        tfBiayaAdm.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel14.setText("Tanda Uji");

        tfBiayaTandaUji.setEditable(false);
        tfBiayaTandaUji.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        tfPokokRetribusi.setEditable(false);
        tfPokokRetribusi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel15.setText("Pokok Terhutang");

        jLabel16.setText("Habis Uji");

        jLabel17.setText("Habis Uji Lalu");

        jLabel18.setText("Denda 2%");

        tfDenda.setEditable(false);
        tfDenda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel19.setText("Total Biaya");

        tfBiaya.setEditable(false);
        tfBiaya.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel20.setText("Bendahara Khusus Penerima");

        cbNamaPejabat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel21.setText("Jabatan");

        tfJabatan.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNoken)
                                    .addComponent(cbJenisKendaraan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfJnsPengujian)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbYa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbTidak)
                                        .addGap(0, 75, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfBiayaBukuUji))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfBiayaTandaUji, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(tfBiayaTandaSamping)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dpTglDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNoUji, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAlamat))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPemilik))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbJnsRumah, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTahunPembuatan, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 115, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfBiayaPemeriksaan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(tfBiayaAdm, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(7, 7, 7))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPokokRetribusi, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7))
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(73, 73, 73)
                                .addComponent(dpTglHabisUji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dpTglHabisUjiLalu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addComponent(jSeparator4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbNamaPejabat, 0, 221, Short.MAX_VALUE)
                            .addComponent(tfJabatan))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dpTglDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNoUji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfPemilik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNoken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbJenisKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbJnsRumah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTahunPembuatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfJnsPengujian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rbYa)
                    .addComponent(rbTidak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(tfBiayaBukuUji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tfBiayaPemeriksaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfBiayaTandaSamping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tfBiayaAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfBiayaTandaUji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPokokRetribusi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(dpTglHabisUji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(dpTglHabisUjiLalu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(tfDenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tfBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cbNamaPejabat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tfJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNoUjiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNoUjiFocusLost
        if(tfNoUji.getText().trim().equals("")) return;
        
        List<AdmKendaraan> dataAdmKendaraan = mainApp.getAdmKendaraanRepo().findByNoUji(tfNoUji.getText());
        tfNoken.setText(((AdmKendaraan) dataAdmKendaraan.get(0)).getNomorKendaraan());
        tfPemilik.setText(((AdmKendaraan) dataAdmKendaraan.get(0)).getNamaPemilik());
        tfAlamat.setText(((AdmKendaraan) dataAdmKendaraan.get(0)).getAlamat());
        cbJenisKendaraan.setSelectedIndex((((AdmKendaraan) dataAdmKendaraan.get(0)).getIdJnsKendaraan() - 1));
        tfTahunPembuatan.setText(((AdmKendaraan) dataAdmKendaraan.get(0)).getThnPembuatan());
        
        List<Skrd> dataSkrd = mainApp.getSkrdRepo().findByNoUjiOrderByTglPemeriksaanDesc(tfNoUji.getText());
        skrd = dataSkrd.get(0);
        dpTglHabisUjiLalu.setDate(skrd.getTglHabisUjiLalu());
        tfBiaya.setValue(getPokok().add(getDenda()));
    }//GEN-LAST:event_tfNoUjiFocusLost

    private void cbJenisKendaraanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbJenisKendaraanItemStateChanged
        // update list jenis rumah-rumah sesuai pilihan ini.
        DefaultComboBoxModel cbModel = new DefaultComboBoxModel();
        Iterator<RefJnsRumah> data = mainApp.getRefJnsRumahRepo().findByIdJnsKendaraan((int) cbJenisKendaraan.getSelectedIndex()+1).iterator();
        while(data.hasNext()) {
            cbModel.addElement(data.next().getJnsRumah());
        }
        cbJnsRumah.setModel(cbModel);
        
        if(cbJenisKendaraan.getItemCount() > 0) {
            List<RefJnsKendaraan> dataJnsKendaraan = mainApp.getRefJnsKendaraanRepo().findById(cbJenisKendaraan.getSelectedIndex() + 1);
            tfBiayaPemeriksaan.setValue(((RefJnsKendaraan) dataJnsKendaraan.get(0)).getTrfPemeriksaan());
        }
        
        rbTidak.setSelected(true);
        
        tfBiayaTandaSamping.setValue(new BigDecimal("15000"));
        tfBiayaAdm.setValue(new BigDecimal("0"));
        tfBiayaTandaUji.setValue(new BigDecimal("10000"));
        if(tfBiayaBukuUji.getValue() != null && tfBiayaPemeriksaan.getValue() != null) {
            tfPokokRetribusi.setValue(getPokok());
            tfDenda.setValue(getDenda());
            tfBiaya.setValue(getPokok().add(getDenda()));
        }
        
        
    }//GEN-LAST:event_cbJenisKendaraanItemStateChanged

    private void rbYaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbYaItemStateChanged
        if(rbYa.isSelected()) {
            List<RefBiayaBukuUji> dataBiayaBujiUji = mainApp.getRefBiayaBukuUjiRepo().findAll();
            tfBiayaBukuUji.setValue(((RefBiayaBukuUji) dataBiayaBujiUji.get(0)).getTarif());
            tfPokokRetribusi.setValue(getPokok());
            tfBiaya.setValue(getPokok().add(getDenda()));
        } else { tfBiayaBukuUji.setText("0"); }
    }//GEN-LAST:event_rbYaItemStateChanged

    private void rbTidakItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbTidakItemStateChanged
        if(rbTidak.isSelected()) {
            tfBiayaBukuUji.setValue(new BigDecimal("0"));
        }
        if(tfBiayaPemeriksaan.getValue() != null) {
            tfPokokRetribusi.setValue(getPokok());
            tfBiaya.setValue(getPokok().add(getDenda()));
        }
    }//GEN-LAST:event_rbTidakItemStateChanged

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(this, "Data akan disimpan.\n" +
                "Apakah data pemilik akan diubah?", "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        if(pilihan == JOptionPane.YES_OPTION) {
            mainApp.fAdmKendaraan.getTfNoken().setText(tfNoken.getText());
            setEnabled(false);
            mainApp.fAdmKendaraan.setVisible(true);
            mainApp.fAdmKendaraan.getTfNoken().requestFocus();
        } else {
            skrd.setBiayaPemeriksaan((BigDecimal) tfBiayaPemeriksaan.getValue());
            skrd.setBiayaBukuUji((BigDecimal) tfBiayaBukuUji.getValue());
            skrd.setBiayaTandaUji((BigDecimal) tfBiayaTandaUji.getValue());
            skrd.setBiayaTandaSamping((BigDecimal) tfBiayaTandaSamping.getValue());
            skrd.setDendaAdm((BigDecimal) tfDenda.getValue());
            skrd.setTglPemeriksaan(dpTglDaftar.getDate());
            skrd.setTglHabisUjiLalu(dpTglHabisUjiLalu.getDate());
            skrd.setTglHabisUjiYad(dpTglHabisUji.getDate());
            if(LocalDate.fromDateFields(skrd.getTglPemeriksaan()).compareTo(LocalDate.fromDateFields(new Date())) == 0) {
                // --------------------------------------------- ini harus uncomment
                //mainApp.getSkrdRepo().save(skrd);
                // ------------------------------------------------------------------------------------
            } else {
                skrd.setId(new Long(mainApp.getSkrdRepo().count() + 1).intValue());
                // ------------------- ini harus uncomment
                //mainApp.getSkrdRepo().save(skrd);
                // ------------------------------------------------------------------------------------
            }
            JOptionPane.showMessageDialog(this, "Data telah tersimpan");
            btnSimpan.setEnabled(false);
            btnCetakFormPendaftaran.setEnabled(true);
            btnCetakSkrd.setEnabled(true);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    
    private BigDecimal getPokok() {
        BigDecimal result = (BigDecimal) tfBiayaBukuUji.getValue();
        result = result.add((BigDecimal) tfBiayaPemeriksaan.getValue());
        result = result.add((BigDecimal) tfBiayaTandaSamping.getValue());
        result = result.add((BigDecimal) tfBiayaAdm.getValue());
        result = result.add((BigDecimal) tfBiayaTandaUji.getValue());
        
        return result;
    }
    
    private BigDecimal getDenda() {
        BigDecimal result = new BigDecimal("0");
        LocalDate tglDaftar = LocalDate.now();
        if(dpTglDaftar.getDate() != null) LocalDate.fromDateFields(dpTglDaftar.getDate());
        LocalDate tglHabisUjiLalu = LocalDate.now();
        if(dpTglHabisUjiLalu.getDate() != null) LocalDate.fromDateFields(dpTglHabisUjiLalu.getDate());
        BigDecimal denda = new BigDecimal("0.02");
        
        if(tglDaftar.isAfter(tglHabisUjiLalu)) {
            BigDecimal pokok = (BigDecimal) tfPokokRetribusi.getValue();
            int selisihBulan = 0;
            if(tglDaftar.getDayOfMonth() > tglHabisUjiLalu.getDayOfMonth()) { 
                selisihBulan = tglDaftar.getMonthOfYear() - tglHabisUjiLalu.getMonthOfYear() + 1;
            } else {
                selisihBulan = tglDaftar.getMonthOfYear() - tglHabisUjiLalu.getMonthOfYear();
            }
            result = result.multiply(pokok);
            result = result.multiply(new BigDecimal(selisihBulan));
        }
        
        return result;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntrySkrdUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntrySkrdUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntrySkrdUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntrySkrdUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntrySkrdUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetakFormPendaftaran;
    private javax.swing.JButton btnCetakSkrd;
    private javax.swing.JButton btnDataBaru;
    private javax.swing.ButtonGroup btnGrpGantiBuku;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbJenisKendaraan;
    private javax.swing.JComboBox<String> cbJnsRumah;
    private javax.swing.JComboBox<String> cbNamaPejabat;
    private org.jdesktop.swingx.JXDatePicker dpTglDaftar;
    private org.jdesktop.swingx.JXDatePicker dpTglHabisUji;
    private org.jdesktop.swingx.JXDatePicker dpTglHabisUjiLalu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JRadioButton rbTidak;
    private javax.swing.JRadioButton rbYa;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JFormattedTextField tfBiaya;
    private javax.swing.JFormattedTextField tfBiayaAdm;
    private javax.swing.JFormattedTextField tfBiayaBukuUji;
    private javax.swing.JFormattedTextField tfBiayaPemeriksaan;
    private javax.swing.JFormattedTextField tfBiayaTandaSamping;
    private javax.swing.JFormattedTextField tfBiayaTandaUji;
    private javax.swing.JFormattedTextField tfDenda;
    private javax.swing.JTextField tfJabatan;
    private javax.swing.JTextField tfJnsPengujian;
    private javax.swing.JTextField tfNoUji;
    private javax.swing.JTextField tfNoken;
    private javax.swing.JTextField tfPemilik;
    private javax.swing.JFormattedTextField tfPokokRetribusi;
    private javax.swing.JFormattedTextField tfTahunPembuatan;
    // End of variables declaration//GEN-END:variables

}
